name: Github Private Package

on:
  release:
    types: [published]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@deskree-inc'

      - name: Install NPM Dependencies
        run: npm install

      - name: Update Project Version
        run: npm version ${{ github.event.release.tag_name }} --no-git-tag-version

      - name: Build project
        run: npm run build

      - run: npm publish --ignore-scripts --tag postman-collection-generator@${{ github.event.release.tag_name }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_ACCESS_TOKEN}}