name: Node.js Package

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Remove .npmrc (This is inteded, to have many npm registry)
        run: rm .npmrc
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Config
        run: npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
      - name: Update Project Version
        run: npm version ${{ github.event.release.tag_name }} --no-git-tag-version
      - name: Push
        run: npm publish --ignore-scripts --tag ${{ github.event.release.tag_name }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
