name: Test
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install NPM Dependencies
        run: npm install

      - name: Run tests and generate JEST coverage report
        run: npm run test
